
CREATE TABLE IF NOT EXISTS film
(
   filmid      int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   name        varchar(200)  NOT NULL,
   description varchar(200)  NOT NULL,
   releasedate date          NOT NULL,
   duration    int           NOT NULL,
   rate        int,
   ratingid    int
);

CREATE TABLE IF NOT EXISTS likes
(
    likeid int  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    userid int  NOT NULL,
    filmid int  NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
    userid   int           GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    varchar(200)  NOT NULL,
    login    varchar(50)   NOT NULL,
    name     varchar(200)  NOT NULL,
    birthday date          NOT NULL
);

CREATE TABLE IF NOT EXISTS friendship (
    friendshipid int   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    userid       int   NOT NULL,
    friendid     int   NOT NULL,
    status       bool
);

CREATE TABLE IF NOT EXISTS genre (
    genreid int          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    varchar(200) NOT NULL
);

CREATE TABLE IF NOT EXISTS genreline (
    filmid      int  REFERENCES film  (filmid) ON DELETE CASCADE,
    genreid     int  REFERENCES genre (genreid),
    PRIMARY KEY (filmid, genreid)
);

CREATE TABLE IF NOT EXISTS ratingmpa (
    ratingid    int           GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        varchar(10)   NOT NULL,
    description varchar(200)  NOT NULL
);